# Dockerfile.gateway
FROM golang:1.23.2 AS builder

WORKDIR /gateway-service
COPY . .

# Cài đặt các phụ thuộc và build ứng dụng Go
RUN go mod download
RUN go build -o api-gateway

# Tạo một image chỉ chứa binary
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /gateway-service/target/api-gateway .

# lắng nghe cổng
EXPOSE 8080  
CMD ["./api-gateway"]
